ZCS-1661 Add support for publishing zip as artifact from any repo
Zimbra/zm-zcs pull request #5
Opened 2017-06-29 21:22 UTC by silentsakky

zm-zcs:ant-global.xml
   - Create a new target zimbra-zip which can be used to publish zips instead of jars from ivy
   - By default jar target will be calling zimbra-jar but caller can override and call zimbra-zip which will publish a zip file
   - removed deploy-foss and publish-foss-local targets as those are related to zm-mailbox which is not using this file currently

zm-zcs:ivysettings.xml
   - when using ivy:install target sometime it was not resolving to proper zip files, so as per suggestion in post http://grokbase.com/t/ant/ivy-user/086ct4mr6h/newbie-cant-resolve-zip-files, I have added ivy pattern line in local resolver

2017-06-29 21:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-zcs?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-zcs?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-zcs?pullRequest=5) it.</sub>

2017-06-30 16:43 UTC, fatkudu requested changes

2017-06-30 16:43 UTC, fatkudu commented on ant-global.xml
>      </target>
Please use a different commit for this unrelated change.

2017-06-30 17:36 UTC, silentsakky commented on ant-global.xml
>      </target>
Thanks
created separate commit for this change, not adding any jira ticket number as this change is not reported anywhere

2017-06-30 19:58 UTC, fatkudu approved these changes

2017-07-04 05:05 UTC, kalpeshhpatel approved these changes

2017-07-10 06:22 UTC, tarangkhandelwal approved these changes

2017-07-10 13:48 UTC, merged